group=net.wechandoit.silverwolfpaper
version=26.2.build.62-beta
mcVersion=26.2

#Update with ASP!! (also update gradle/libs.versions.toml)
aspRef=e50e53068572787b914b8d4b86dc3ccf4391f6e8
aspApiVersion=4.2.0-SNAPSHOT
apiVersion=26.2

org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

org.gradle.jvmargs=-Xmx4G