group=net.wechandoit.silverwolfpaper
version=26.2.build.62-beta
mcVersion=26.2

#Update with ASP!! (also update gradle/libs.versions.toml)
aspRef=a461b922fbdae8577717342741adda0b79554a9b
aspApiVersion=4.2.0-SNAPSHOT
apiVersion=26.2

org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

org.gradle.jvmargs=-Xmx4G