group=net.wechandoit.silverwolfpaper
version=26.1.2.build.61-stable
mcVersion=26.1.2

#Update with ASP!! (also update gradle/libs.versions.toml)
aspRef=2e69d9f6e20da479e8a3edea0a57ce1a16888fe7
aspApiVersion=4.2.0-SNAPSHOT
apiVersion=26.1.2

org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

org.gradle.jvmargs=-Xmx4G